# Generated by Django 4.2.3 on 2023-10-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('loc', models.CharField(max_length=50)),
                ('fbook', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
    ]
