# Generated by Django 4.2.3 on 2023-10-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_userprofilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='audiobookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=100)),
                ('afile', models.FileField(upload_to='book_app/static')),
                ('aboutaud', models.CharField(max_length=500)),
            ],
        ),
    ]
